### ISSUE TITLE
Error running CLI

### ISSUE THREAD

**Issue by jasonlarocque** [akamai/cli-netstorage#10]
Running from Windows 10 device:
C:\akamai>akamai netstorage --config rsassets-dev-auth du
Getting disk usage information
C:\snapshot\cli-netstorage\node_modules\request\request.js:186
      self._callback.apply(self, arguments)
                     ^

TypeError: Cannot read property 'statusCode' of undefined
    at __dirname.makeRequest.Promise._nsClient.send (C:\snapshot\cli-netstorage\src\netstorage.js:0:0)
    at NetStorageAuth.<anonymous> (C:\snapshot\cli-netstorage\src\netstorage_auth.js:0:0)
    at Request.init.self.callback (C:\snapshot\cli-netstorage\node_modules\request\request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\snapshot\cli-netstorage\node_modules\request\request.js:878:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)

No matter what I run, I get this error. Please let me know if you need any other info. Thanks in advance for your help!

**Comment by manojchandrashekar** [comment]
I know this is an old one, but I faced the same issue yesterday.

Clearing the DNS cache worked for me.
