### ISSUE TITLE
Akamai symlink is not defined in cli

### ISSUE THREAD

**Issue by asingh64** [akamai/cli-netstorage#11]
When Trying the symlink I am seeing below error. Looks like symlink is missing in 'src/netstorage.js'

$ akamai netstorage symlink ‘root/AmitTest/version.txt’ ‘root/AmitTest/version1.txt’ --config '/Users/******/.akamai-cli/.netstorage/auth_OHWprd'

ERROR: 
	 TypeError: app.symlink is not a function
    at symlink (/Users/*/.akamai-cli/src/cli-netstorage/bin/akamaiNetstorage:114:14)
    at TypeCommand.run [as _runHandler] (/Users/*/.akamai-cli/src/cli-netstorage/bin/akamaiNetstorage:309:18)
    at api.parseFromContext.then.whenDone (/Users/*/.akamai-cli/src/cli-netstorage/node_modules/sywac/types/command.js:130:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
$

**Comment by v0d** [comment]
confirmed. the feature is still missing

**Comment by lufo0** [comment]
Hi,
I implemented this a few days ago in Pull Request #17. It says it fails CI but I believe it's because the test suite is not correctly defined (credentials seem to be missing).
Give it a try if you wish, it worked for me (note: "target" and "path" meaning and order are confusing, try it the other way around if it does not work at first).
