### ISSUE TITLE
Error while running akamai netstorage list <cpcode>

### ISSUE THREAD

**Issue by Venkata-Kolla** [akamai/cli-netstorage#26]
Hi,
I have followed all the instructions and installed Akamai CLI for Netstorage, but am receiving the following error while running the command  `akamai netstorage list <cpcode>`

vkolla$ akamai netstorage list <cpcode>
Getting directory listing/snapshot/cli-netstorage/node_modules/request/request.js:186self._callback.apply(self, arguments)^TypeError: Cannot read property 'statusCode' of undefinedat __dirname.makeRequest.Promise._nsClient.send (/snapshot/cli-netstorage/src/netstorage.js:0:0)at NetStorageAuth.<anonymous> (/snapshot/cli-netstorage/src/netstorage_auth.js:0:0)at Request.init.self.callback (/snapshot/cli-netstorage/node_modules/request/request.js:186:22)
--

Please include [AKAM-CASE #F-CS-5905164] in the subject line when emailing Akamai about this case.

**Comment by MattMcFarland** [comment]
I think <cpcode> is the actual cdcode not `<cpcode>`

You would be running it like this:
```
$ akamai netstorage list 1234
```
but only if `1234` was the cpcode you wanted to use...
